
baseURL: "https://dig404.com/"
title: "多元生活"
theme: "ananke"
Paginate: 10
enableRobotsTXT: true
# sectionPagesMenu: "main"

params:
  style: "default"
  AuthorName: "有福"
  GitHubUser: "chenyoufu"
  SidebarRecentLimit: 5
  gitment: false
  mainSections: ["photos"]
  recent_posts_number: 10

menu:
  main:
      
      - name: "图"
        pre: "<i class='fa fa-road'></i>"
        weight: -150
        url: "/photos/"
      - name: "书"
        pre: "<i class='fa fa-road'></i>"
        weight: -130
        url: "/books/"
      - name: "文"
        pre: "<i class='fa fa-road'></i>"
        weight: -140
        url: "/posts/"
      - name: "杂"
        pre: "<i class='fa fa-road'></i>"
        weight: -120
        url: "/misc/"

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

imaging:
  resampleFilter: "box"
  quality: 100
  anchor: "smart"